version: "3"
services:
  node-api:
    restart: always
    build:
      context: .
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}" 
    ports:
      - "8001:8000"
    volumes:
      - ".:/usr/src/app"
      - "./docker/logs:/usr/src/app/docker/logs"
    networks:
      - node
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      NODE_ENV: development
      TZ: UTC
    user: "${UID:-1000}:${GID:-1000}"

  mysql:
    restart: always
    image: mariadb:10.2.43
    container_name: mysql-node
    volumes:
      - node-data:/var/lib/mysql
    networks:
      - node
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: etas
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: etas
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password

volumes:
  node-data:

networks:
  node:
    driver: bridge
