version: "3"
services:
  node-api:
    build:
      context: .
      args:
        WWWGROUP: "${WWWGROUP}"
    ports:
      - "8000:8000"
    volumes:
      - ".:/usr/src/app" # Mapeo del directorio de trabajo del proyecto al contenedor
    networks:
      - node
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      # Otras variables de entorno necesarias
  mysql:
    image: mariadb:10.2.43
    container_name: mysql-node
    volumes:
      - node-data:/var/lib/mysql
    networks:
      - node
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: etas
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # Esto permite que el usuario root se conecte sin contraseña
      MYSQL_USER: etas
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "81:80"
    networks:
      - node
    environment:
      #PMA_ARBITRARY: 1
      # PMA_PORT: 3306
      PMA_HOST: mysql-node
      PMA_USER: "root"
      PMA_PASSWORD: "password"
      # PMA_ROOT_PASSWORD: ""
volumes:
  logs: #
  node-data:

networks:
  node:
    driver: bridge

#Run on casa
x-casaos:
  scheme: http
  # index: /
  port_map: "89"
  author: self
  category: self
  icon: http://192.168.112.2/nodejs-icon-logo-svgrepo-com.svg
  title:
    custom: API ETAS
